### ISSUE TITLE
Nerf screamers

### ISSUE THREAD

**Issue by CWorm** [CWorm/zspussfoot#7]
Current damage and stamina drain is too high for their HP.

**Comment by CWorm** [comment]
Calico Jack Azurackham: or:
Calico Jack Azurackham: make screamers have only like 50 hp
Calico Jack Azurackham: would be a high risk high reward class
Calico Jack Azurackham: and pretty much a ninja class

**Comment by Azurblau** [comment]
Simply nerfed them now. The ninja variant could be a separate class if ever.
